name: 'speckle-server'

services:
  speckle-frontend-2:
    ports:
      - '0.0.0.0:80:8080'

  speckle-server:
    ports:
      - '0.0.0.0:3000:3000'

  minio:
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:9001:9001'
